### ISSUE TITLE
可以配合 capmonster.cloud 做到自动化吗？

### ISSUE THREAD

**Issue by wc7086** [timlzh/openAI-Auto-Registration#3]

**Comment by timlzh** [comment]
全自动化的话可能还需要一个邮箱服务器

**Comment by wc7086** [comment]
> 全自动化的话可能还需要一个邮箱服务器

邮箱简单啊，卖邮箱的都开通好 IMAP 了，直接用 IMAP 登录等激活右键就行了，主要是没搞明白 capmonster.cloud 怎么用

**Comment by wc7086** [comment]
https://github.com/alperensert/capmonster_python/tree/master/examples

可以参考这里，我还有其他事要做，暂时没空搞

**Comment by timlzh** [comment]
好的，我看看
